[package]
name = "pkombi"
version = "0.2.0"
edition = "2021"
readme = "README.md"
license = "MIT"
description = "Parser combinator library"
repository = "https://github.com/prodbysky/pkombi"
keywords = ["parser", "combinator"]
categories = ["parsing"]

[dependencies]
